trigger:
- main

schedules:
- cron: '0/30 * * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: dotnet sdk
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '2.x'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-reventuregame'
    organization: '2102-feb08-net'
    scannerMode: 'MSBuild'
    projectKey: '2102-feb08-net_Game-Server'
    projectName: 'Game-Server'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: dotnet build
  workingDirectory: 'Game-Server-Solution'

# - task: DotNetCoreCLI@2
#   displayName: dotnet test
#   inputs:
#     command: 'test'
#     arguments: '--configuration $(buildConfiguration) --collect "xplat code coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'
#     workingDirectory: 'Game-Server'


- task: SonarCloudAnalyze@1
  displayName: sonar run analysis

- task: SonarCloudPublish@1
  displayName: publish sonar quality gate
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@1
  displayName: publish code coverage report
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'

